#!/bin/bash

#
# Retrieve availability_zone from AWS instance
# rein 2016
#
# From: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
#
availability_zone=$( curl --max-time 50000 --retry 12 --retry-delay 50000 http://169.254.169.254/latest/meta-data/placement/availability-zone -s -S )
if [ ! "$availability_zone" ]; then
	echo Unable to retrieve Instance Availability Zone from instance metadata server 1>&2
	exit 99
fi

echo "$availability_zone"
