#!/bin/bash

#
# Retrieve Update Domain for azure instance
# rein 2016
#

# curl http://169.254.169.254/metadata/v1/InstanceInfo ; echo ''
# produces
# {"ID":"_dc1vm0","UD":"1","FD":"1"}

update_domain=$(curl --max-time 50000 --retry 12 --retry-delay 50000 http://169.254.169.254/metadata/v1/InstanceInfo -s -S | sed -e 's/.*"UD":"\([^"]*\)".*/\1/')
if [ ! "$update_domain" ]; then
	echo Unable to retrieve Instance Update Domain from instance metadata server 1>&2
	exit 99
fi

echo "$update_domain"