#!/bin/bash

#
# Retrieve Instance ID for azure instance
# rein 2016
#

# curl http://169.254.169.254/metadata/v1/InstanceInfo ; echo ''
# produces
# {"ID":"_dc1vm0","UD":"1","FD":"1"}

instance_id=$(curl http://169.254.169.254/metadata/v1/InstanceInfo -s -S | sed -e 's/.*"ID":"\([^"]*\)".*/\1/')
if [ ! "$instance_id" ]; then
	echo Unable to retrieve Instance ID from instance metadata server 1>&2
	exit 99
fi

echo "$instance_id"