#!/usr/bin/env bash
#
# Show cassandra cluster internal and external addresses
# uses nodetool to get internal addresses and icanhazip.com for external addressses
#

# cassandra_node_sstable_count_by_size_magnatude [directory]

[ "root" != "$USER" ] && exec sudo $0 "$@"

list_file_sample=0
if [ x"$1" == "x-s" ]; then list_file_sample=1; shift; fi
if [ x"$1" != x ]; then cd "$1"; fi

count_db_files () {
        min_size=$1
        max_size=$2
        #set -x 
        file_count=$(find . -name '*Data.db' -type f -size +${min_size}c -size -${max_size}c -print | grep -v '/snapshots/' | grep -v '/backups/' | wc -l )

        printf '%20s %20s %20s\n' $min_size $max_size $file_count
	if [ 0 != $file_count ]; then
		if [ $list_file_sample != 0 ]; then
			find $(pwd) -name '*Data.db' -type f -size +${min_size}c -size -${max_size}c -print | grep -v '/snapshots/' | grep -v '/backups/' | head -n 1
		fi
	fi

}

lower=1
power=2 # for 2x and 10x
until [  $lower -gt 99999999999999999 ]; do
	upper=$((power*lower-1))
	count_db_files $lower $upper
	lower=$((upper+1))
done

