#!/bin/bash

if [ x"$1" == x"-n" ]; then
	shift
	lines="$1"; shift
else
	lines=9999999
fi

if [ x"$1" == x ]; then
	dir=$(pwd)
else
	dir="$1"; shift
	if [ ! -d "$dir" ]; then
		echo Error: "$dir" is not a directory; exit 99;
	fi
fi


#dir='/Users/richrein/dse/data'
printf "%24s   %s\n" "total bytes" "Table directory" 
du -sb "$dir/"*/* | (while read size table ; do printf '%24d   %s\n' $size "$table"; done ) | sort -nk1 | tail -n $lines
