#!/usr/bin/env bash
#
#

# cassandra_sstable_compaction_byte_rate

val1=`nodetool compactionstats | grep Compaction | awk '{sum+=$4} END {print sum}'`
sleep 60; 
val2=`nodetool compactionstats | grep Compaction | awk '{sum+=$4} END {print sum}'`; 
let val3="($val2-$val1)/(1024*1024)"
echo $val3
