#!/usr/bin/env sudo bash

if [ "x$1" == "x" ]; then
	echo "Error:     " `basename $0`: First argument must be the name of a directory containing Cassandra sstables within.
	echo ""
	echo "Examples: $" `basename $0` /Users/richrein/dse
	echo "          $" `basename $0` /Users/richrein/dse/data/system
	echo ""
	exit 99
fi
DIRNAME="$1"
if [ ! -d "$DIRNAME" ]; then
	echo "Error:     " `basename $0`: First argument \""$DIRNAME"\" does not refer to a valid directory
	echo ""
	echo "Examples: $" `basename $0` /Users/richrein/dse
	echo "          $" `basename $0` /Users/richrein/dse/data/system
	echo ""
	exit 99
fi

printf 'sstable versions on storage\n'
find "$DIRNAME" -type f -name '*-Data.db' | sed -e 's/.*-\(..\)-[0-9]*-Data.db$/\1/'  | sort | uniq -c | while read count version
do
	printf '%7s sstables in %2s format.\n' $count $version 
done 
