#!/usr/bin/env bash
#
# Show cassandra cluster internal and external addresses
# uses nodetool to get internal addresses and icanhazip.com for external addressses
#

rowFormat="%-20s %-20s\n"

nodetool status \
| sed -e 's:[^0-9.]*\([0-9.]*\).*:\1:' \
| grep '[0-9]' \
| (printf "$rowFormat" "Internal IP" "External IP"; 
	while read localIp ; do 
		printf "$rowFormat" $localIp `ssh ubuntu@$localIp curl -s icanhazip.com </dev/null`
	done
) | col -b


