#!/bin/bash


if [ x"$1" == x'-n' ]; then
	shift
	lines=$1; shift
else
	lines=999999
fi

if [ x"$1" == x ]; then
	dir=$(pwd)
else
	dir="$1"; shift
	if [ ! -d "$dir" ]; then
		echo Error: "$dir" is not a directory; exit 99;
	fi
fi


#dir='/Users/richrein/dse/data'
printf "%10s   %s\n" "sstables" "Table directory" 
(
	for tabledir in "$dir"/*/* ; do
		printf "%10d   %s\n" $(ls -f $tabledir/*Data.db 2>&- | wc -l) $tabledir 
	done
) | sort -nk1 | tail -n $lines
