#!/usr/bin/env bash


# allow invokation of related scripts in this dir
scriptdir=`dirname "$BASH_SOURCE"`; PATH="$scriptdir:$PATH"


if [ x"$1" == x ]; then 
	echo missing process id
	echo "$(basename $0) pid"
	exit 1
else
	jpid=$1
fi


jstat -gcutil -h10 -t $jpid 250ms 0


