#!/usr/bin/env bash

#
# ctool_allow_mutual_access - join 2 or more ctool clusters in key sharing and internode ip access permissions
#
# Allows access any node from any node with either private key. 
#
# Usage: ctool_allow_mutual_access cluster1 cluster2 clusterN`
#
# Gives all nodes in all clusters access to each other’s ips.
# The public keys for all clusters are in each others .ssh/authorized_keys files.
#
# Rich Rein 2019 Apache 2.0 license
#

# allow invokation of related scripts in this dir
scriptdir=`dirname "$BASH_SOURCE"`; PATH="$scriptdir:$PATH"

OS_FLAVOR=$(os_flavor)
case $OS_FLAVOR in
	osx) 	;;
	ubuntu) ;;
    linux) ;;
	*) echo $OS_FLAVOR not supported; exit 1;;
esac

verbose=false
if [ x"$1" != x ]; then
	if [ x"$1" = x-v ]; then
		verbose=true
		shift
	fi
fi

#
# Allow_access between all node private and public ips
#
ips="$(echo $(
	(
		for (( i=1; i <= "$#"; i++ )); do
		    cluster="${!i}"
		    ctool info $cluster
		done
	) | grep ' ip:' | sed -e 's/.*:\(.*\)/\1/' 
) | sed -e 's/ /,/g' ) " 


for (( i=1; i <= "$#"; i++ )); do
    cluster="${!i}"
	( if [ $verbose == true ]; then set -x; fi

		ctool allow_access $cluster $ips
	)
done

#
# Copy all public and private keys to all nodes
#
(
	for (( i=1; i <= "$#"; i++ )); do
		for (( j=1; j <= "$#"; j++ )); do
			clusterSrc="${!i}"
			clusterDst="${!j}"
			(
				set -x
				ctool scp $clusterDst all /Users/richrein/.automaton/*/*/$clusterSrc/public_key ${clusterSrc}_pub
				ctool scp $clusterDst all /Users/richrein/.automaton/*/*/$clusterSrc/private_key ${clusterSrc}_pri
			)
		done
	done

)

#
# Append public keys on nodes onto .ssh/authorized_keys
#
(
	for (( i=1; i <= "$#"; i++ )); do
		cluster="${!i}"
		public_ips="$(echo $(ctool info $cluster | grep 'public ip:' | sed -e 's/.*:\(.*\)/\1/' ))"
		echo cluster $cluster pub $public_ips
		for public_ip in $public_ips; do
			(
				# Append public keys
				set -x
				ssh -i $HOME/.automaton/*/*/$cluster/private_key automaton@$public_ip  cat \*_pub \>\> .ssh/authorized_keys 
			)
		done
	done
)

