#!/usr/bin/env bash

OS_FLAVOR=$(os_flavor)
case $OS_FLAVOR in
	osx) 	;;
	*) echo $OS_FLAVOR not supported; exit 1;;
esac



showSeparator () {
	echo "" 
}

showPort () {
	if [ x$1 = x ]; then echo "`basename $0`: Internal error. ShowPort missing port arg"; exit; fi
	portNumber="$1"; shift
	if [ x$1 = x ]; then echo "`basename $0`: Internal error. ShowPort missing port description"; exit; fi
	portDescription="$@"; shift

	portCount_prior=$portCount
	portCount=$(ip_port_process_count $portNumber)

	if [ $portCount_prior != 0 ]; then
		showSeparator;
	else
		if [ $portCount_prior != 0 ]; then 
			showSeparator;
		fi
	fi

	printf "Port %5s %s - %s\n" "$portNumber" "($portCount)" "$portDescription"
	if [ $portCount != 0 ]; then 
		ip_port_process_list $portNumber;
	fi
}

showSection () {
	if [ x$1 = x ]; then echo "`basename $0`: Internal error. ShowPort missing port description"; exit; fi
	sectionDescription="$@"; shift

	showSeparator;

	printf "%s\n" "$sectionDescription"
	firstSection=false
	portCount=0
	portCount_prior=0

}



showSection	OpsCenter
showPort 22		SSH \(opscenterd.conf\)
showPort 8888	OpsCenter website
showPort 50031	OpsCenter HTTP proxy for Hadoop job browsing
showPort 61620	OpsCenter listening for traffic from agent

showSection	Cassandra
showPort 9042	CQL client Native Transport port \(cassandra.yaml\)
showPort 9160	Cassandra Thrift RPC port
showPort 7000	Cassandra inter-node storage port
showPort 7001	Cassandra inter-node ssl storage port
showPort 7199	Cassandra JMX port

showSection Spark
showPort 7077	Spark Master inter-node port \(dse.yaml\)
showPort 4040	Spark application website port
showPort 7080	Spark Master web site port \(spark-env.sh\)
showPort 7081	Spark Worker web site port \(spark-env.sh\)

showSection Solr 
showPort 8983	Solr port and demo app website port 
showPort 8984	Solr inter-node communication port \(dse.yaml\) 

showSection Hadoop
showPort 8012	Hadoop Job Tracker client port
showPort 9000	Hadoop NameNode port
showPort 9290	Hadoop Job Tracker OpsCenter Thrift port
showPort 10000	Hadoop Hive\/Shark server port \(hive-site.xml\)
showPort 10001	Hive Spark SQL Thrift Server 
showPort 50030	Hadoop Job Tracker website port
showPort 50060	Hadoop Task Tracker website port

