#!/usr/bin/env bash

for directory in $(dse_path_cassandra_directory_suspect_list)
do
	saved_caches_directory="$directory/saved_caches"
        if [ -d "$saved_caches_directory" ]; then echo "$saved_caches_directory"; exit 0; fi
done
echo NOTFOUND; exit 99;

