#!/usr/bin/env bash

for directory in "/mnt/cassandra", "$HOME/dse"
do
        directory="$directory/commitlog"
        if [ -d "$directory" ]; then echo "$directory"; exit 0; fi
done
echo NOTFOUND; exit 99;

