#!/usr/bin/env bash


###
### Script to ask ec2 or other for current address
###
### Rich Rein
###
###
### TODO: Add remote node lookup if local ip given as arg:
###    ssh ubuntu@$localIp curl -s 'http://checkip.dyndns.org' | sed 's/.*Current IP Address: \([0-9\.]*\).*/\1/g'
###

###
### global methods
###
#curl -s icanhazip.com
#curl --max-time 50000 --retry 12 --retry-delay 50000 -s 'http://checkip.dyndns.org' | sed 's/.*Current IP Address: \([0-9\.]*\).*/\1/g'
curl --max-time 5000 --retry 12 --retry-delay 5000 -s 'http://checkip.dyndns.org' | sed 's/.*Current IP Address: \([0-9\.]*\).*/\1/g'

###
### EC2 only methods
###
# curl http://169.254.169.254/latest/meta-data/public-ipv4
# wget -qO- http://instance-data/latest/meta-data/public-ipv4
