#!/usr/bin/env bash

#
# List processes that have the port open
#

# make sure running as root
if [[ $EUID -ne 0 ]]; then echo "Error: Run $(basename $0) as root"; exit 1; fi

OS_FLAVOR=$(os_flavor)

if [ x$1 = x ]; then echo "`basename $0`: Error - Missing port arg"; exit; fi
portNumber="$1"; shift

case $OS_FLAVOR in
	osx)	lsof -nPR -i :$portNumber ;;
	ubuntu)	lsof -nPR -i :$portNumber ;;
	linux)	lsof -nPR -i :$portNumber ;;
	*) echo $OS_FLAVOR not supported; exit 1;;
esac
