#!/usr/bin/env bash

#
# Show number of processes that have the port open
#

# make sure running as root
if [[ $EUID -ne 0 ]]; then echo "Error: Run $(basename $0) as root"; exit 1; fi

if [ x$1 = x ]; then echo "`basename $0`: Internal error. ShowPort missing port arg"; exit; fi
portNumber="$1"; shift

OS_FLAVOR=$(os_flavor)

case $OS_FLAVOR in
	osx)	lsof -nPR -i :$portNumber | sed -e '1d' | wc -l | sed -e 's/ //g' ;;
	ubuntu)	lsof -nPR -i :$portNumber | sed -e '1d' | wc -l | sed -e 's/ //g' ;;
	*) echo $OS_FLAVOR not supported; exit 1;;
esac
