#!/usr/bin/env bash

#
## Script for downloading scheme.xml for DSE 4.8 Solr
#

user=":"
#user="myuser"
#user="myuser:mypassword"

ipaddr=$(ip_address_private)
#ipaddr="66.79.80.64"

core="x.y"
#core="mykeyspace.mytable"

echo $ipaddr, $core >&2
answer=`printf '%s' 'Parameters OK? ' >&2; read val; echo $val;`;
if [ x$answer != x"yes" ]; then echo cancelled; exit 1; fi

set -e
set -x
:
: Download the schema to edit
curl -u "$user" "http://$ipaddr:8983/solr/$core/admin/file?file=schema.xml&contentType=text/xml;charset=utf-8"

exit 0 


# Notes
#curl "http://$ipaddr:8983/solr/resource/$core/admin/files?file=schema.xml" --data-binary @schema.xml -H 'Content-type:text/xml; charset=utf-8'
#curl -u $user http://$ipaddr:8983/solr/resource/$core/admin/files?file=schema.xml --data-binary @schema.xml -H 'Content-type:text/xml; charset=utf-8'
#curl -u $user http://$ipaddr:8983/solr/#/$core/admin/files?file=schema.xml --data-binary @schema.xml -H 'Content-type:text/xml; charset=utf-8'
