#!/usr/bin/env bash

OS_FLAVOR=$(os_flavor)
case $OS_FLAVOR in
	osx) 	;;
	ubuntu) ;;
     linux) ;;
	*) echo $OS_FLAVOR not supported; exit 1;;
esac

if [ x"$1" == x ]; then
	echo "Error: $(basename "$0") - Missing timestamp"
	echo 'Example:'
	echo 'Given microseconds show date, time'
	echo "\$ `basename $0` 1462496302000000"
	echo '2016-05-05 1758'
	exit 99
fi

seconds=$(echo $1 | sed -e 's/\(.*\)....../\1/')

if [ $OS_FLAVOR == osx ]; then
	(set -x; date -j -f %s "$seconds" '+%Y-%m-%d %H%M')
else
	(set -x; date --date="1970-01-01 $seconds sec" '+%Y-%m-%d %H%M')
fi


# ------------------------------------------------------------
# Bash - OSx
# ------------------------------------------------------------
# Get current time in seconds
# $ date +%s
# 1453819003

# Get human readable date given the time in seconds
# $ date -j -f %s 1462455405 '+%Y-%m-%d %H%M'
# 2016-05-05 0636

# Get current time in microseconds  (for CQL)
# $ date +%s000000
# 1453819003000000

# Get current time + 100 days in microseconds
# $ date -v+100d +%s000000
# 1462455405000000

# ------------------------------------------------------------
# Bash - Gnu Linux
# ------------------------------------------------------------
# Get current time in seconds
# $ date +%s
# 1453821223

# Get current time in microseconds  (for CQL)
# $ date +%s000000
# 1453819003000000

# Get current timestamp + 100 days in microseconds
# $ date --date='100 day' +%s000000
# 1462498323000000

# Get current timestamp + 2 days prior in microseconds
# $ date --date='2 days ago' +%s000000
# 1453685542000000

# Get current timestamp for + 3 months and 1 day later in microseconds
# $ date --date='3 months 1 day' +%s000000
# 1461806789000000

# Get human readable date given the time in seconds
# $ date -d '1970-01-01 1453819003 sec' '+%Y-%m-%d %H%M'
# 2016-01-26 1436

# Get current time + 100 days in microseconds
# $ date --date='100 day' '+%Y-%m-%d %H%M'
# 2016-05-05 1509

# Get current time + 2 days prior in microseconds
# $ date --date='2 days ago' '+%Y-%m-%d %H%M'
# 2016-01-24 1507

# Get current time + 3 months and 1 day later in microseconds
# $ date --date='3 months 1 day' '+%Y-%m-%d %H%M'
# 2016-04-27 1508

# Gnu Date - http://ss64.com/bash/date.html 


